german translation
TalismanSociety/talisman-web pull request #203
Opened 2022-01-05 16:42 UTC by PieWol

2022-01-05 20:35 UTC, Kiruse commented on public/locales/ger/connect-wallet.json
> +  "TOS": "Durch Verbinden einer Wallet akzeptierst du unsere 1>Nutzungsbedingungen</1>"
Is this missing an opening tag (`<`)?

2022-01-05 21:12 UTC, PieWol commented on public/locales/ger/connect-wallet.json
> +  "TOS": "Durch Verbinden einer Wallet akzeptierst du unsere 1>Nutzungsbedingungen</1>"
yeah, sadly it is.

2022-01-05 23:54 UTC, juliuscarvajal commented on public/locales/ger/languages.json
> +  "ru": "Русский"
Please add the German lang here. Should it be `deu` instead of `ger`?

2022-01-05 23:57 UTC, juliuscarvajal commented on public/locales/ger/languages.json
> +  "ru": "Русский"
Please add to this file as well `src/libs/i18n/i18n.ts` under `fallbackLangs`

2022-01-05 23:58 UTC, juliuscarvajal commented
Thanks @PieWol for this. Just some minor comments.

2022-01-06 00:00 UTC, juliuscarvajal commented on public/locales/ger/banners.json
> +    "description": "Show me the money",
Missed translation

2022-01-06 00:14 UTC, DerTiedemann approved these changes
MInor things, though LGTM!
![Leo Clap](https://media.giphy.com/media/gLu90OMjz4j3hAkJk2/giphy.gif)

2022-01-06 00:14 UTC, DerTiedemann commented on public/locales/ger/banners.json
> +    "description": "Kaufe DOT und KSM mit crypto oder deiner Kreditkarte",
Crypto with a capital C?

2022-01-06 00:14 UTC, DerTiedemann commented on public/locales/ger/languages.json
> +  "ru": "Русский"
Accoring to ISO-3166 `DE` is the short country code for Germany. This is informed by [this](https://www.iso.org/obp/ui/#iso:code:3166:DE) site. Futhermore [il8n](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n) uses this schema.

2022-01-06 00:14 UTC, DerTiedemann commented on public/locales/ger/crowdloan.json
> +    "feeNote": "Bitte beachte, dass für diese Signierungstransaktion Transaktionsgebühren im Polkadot-Netzwerk anfallen (ca. 0,0411 DOT) und Polkadot einen Mindestkontostand von 1 DOT verlangt.",
This is not specific to the translation, but I have a big problem with the fact that fees are just hardcoded here. Governace and chain congestion can alter this dramaticlly, so a dynamic value is imho required.

2022-01-06 00:14 UTC, DerTiedemann commented on public/locales/ger/banners.json
> +    "description": "Show me the money",
```suggestion
    "description": "Zeig mir meinen Kontostand!",

```

2022-01-06 00:39 UTC, juliuscarvajal commented on public/locales/ger/crowdloan.json
> +    "feeNote": "Bitte beachte, dass für diese Signierungstransaktion Transaktionsgebühren im Polkadot-Netzwerk anfallen (ca. 0,0411 DOT) und Polkadot einen Mindestkontostand von 1 DOT verlangt.",
Agreed on dynamic values for fees. This is for Moonbeam Crowdloan which was already done so should be ok.

2022-01-06 07:24 UTC, PieWol commented on public/locales/ger/languages.json
> +  "ru": "Русский"
I didn't modify this file because it seemed to me that none of the other translations have a modified version of this file or their respective language included. Should I still change it? Will rename it to `de`

2022-01-06 07:42 UTC, juliuscarvajal commented
@PieWol final bit is to rename the folder from `ger` to `de`.
Then add `"de": "German"` to `languages.json`.
Then in `src/libs/i18n/i18n.ts`, add `de` to `fallbackLngs`.

2022-01-06 15:28 UTC, Kiruse requested changes
A couple suggestions about grammar & anglicisms.

2022-01-06 15:28 UTC, Kiruse commented on public/locales/ger/crowdloan.json
> +    "description": "Durch Klicken \"Signieren und Abschicken\" unten, wird deine Zustimmung, in Verbindung mit deinem DOT Konto, zu den Moonbeam Crowdloan Geschäftsbedingungen 'on chain' gespeichert.
Should read, imo:

> Durch Klicken **auf** \\"Signieren und Abschicken\\" unten wird deine Zustimmung, ...

Note that the first comma should be removed as well.

2022-01-06 15:28 UTC, Kiruse commented on public/locales/ger/spirit-keys.json
> +      "Der Talisman <1>Discord server</1>",
Anglicized noun "Discord Server"

2022-01-06 15:28 UTC, Kiruse commented on public/locales/ger/spirit-keys.json
> +      "Teilnahme an community calls und Events",
Angliziced noun "Community Calls"

2022-01-06 23:20 UTC, juliuscarvajal commented on public/locales/ger/crowdloan.json
> +    "description": "Durch Klicken \"Signieren und Abschicken\" unten, wird deine Zustimmung, in Verbindung mit deinem DOT Konto, zu den Moonbeam Crowdloan Geschäftsbedingungen 'on chain' gespeichert.
@Kiruse thanks for this. Would be good to use the "Insert a suggestion <cmd-g>" so that we can merge that suggestion immediately. It's the folder looking icon with plus and minus stacked vertically.

2022-01-06 23:28 UTC, Kiruse requested changes

2022-01-06 23:28 UTC, Kiruse commented on public/locales/ger/crowdloan.json
> +    "description": "Durch Klicken \"Signieren und Abschicken\" unten, wird deine Zustimmung, in Verbindung mit deinem DOT Konto, zu den Moonbeam Crowdloan Geschäftsbedingungen 'on chain' gespeichert.
```suggestion
    "description": "Durch Klicken auf \"Signieren und Abschicken\" unten wird deine Zustimmung, in Verbindung mit deinem DOT Konto, zu den Moonbeam Crowdloan Geschäftsbedingungen 'on chain' gespeichert. Dies geschieht in Form einer von deinem Konto signierten Nachricht.",
```

2022-01-06 23:28 UTC, Kiruse commented on public/locales/ger/languages.json
> +  "ru": "Русский"
```suggestion
  "ru": "Русский",
  "de": "Deutsch"
```

2022-01-06 23:28 UTC, Kiruse commented on public/locales/ger/spirit-keys.json
> +      "Early access zu neuen Funktionen in der Talisman Web App"
```suggestion
      "Early Access zu neuen Funktionen in der Talisman Web App"
```

2022-01-06 23:28 UTC, Kiruse commented on public/locales/ger/spirit-keys.json
> +      "Der Talisman <1>Discord server</1>",
```suggestion
      "Der Talisman <1>Discord Server</1>",
```

2022-01-06 23:28 UTC, Kiruse commented on public/locales/ger/spirit-keys.json
> +      "Teilnahme an community calls und Events",
```suggestion
      "Teilnahme an Community Calls und Events",
```

2022-01-06 23:28 UTC, Kiruse commented on public/locales/ger/crowdloan.json
> +    "description": "Durch Klicken \"Signieren und Abschicken\" unten, wird deine Zustimmung, in Verbindung mit deinem DOT Konto, zu den Moonbeam Crowdloan Geschäftsbedingungen 'on chain' gespeichert.
@juliuscarvajal Sweet, I was wondering where this option was. Thanks. Posted.

2022-01-07 03:01 UTC, juliuscarvajal commented on public/locales/ger/languages.json
> +  "ru": "Русский"
As discussed, no need to change in this PR. I'll do the change once the PR is merged.

2022-01-07 03:06 UTC, merged