multichain transaction history proof-of-concept
TalismanSociety/talisman-web pull request #298
Opened 2022-09-01 10:13 UTC by alecdwm

2022-10-19 14:52 UTC, alecdwm reviewed
Added a few notes, mostly unused functions/components which I'll remove in a commit tomorrow.

2022-10-19 14:52 UTC, alecdwm commented on src/components/Panel.tsx
> +    overflow: hidden;
Will remove this, it breaks the portfolio panel

2022-10-19 14:52 UTC, alecdwm commented on src/util/useTimeout.ts
> +import { useCallback, useState } from 'react'
`useTimeout` isn't used anywhere in the final version of this PR, I will remove it.

2022-10-19 14:52 UTC, alecdwm commented on src/archetypes/Chain/LogoById.tsx
> +export default styled(({ id, className }: Props) => {
I will remove this component, it's not used anywhere in the final version of this PR.

2022-10-19 14:52 UTC, alecdwm commented on src/archetypes/Account/Picker.tsx
> +const AccountPicker = styled(({ className, onChange, showAllAccounts = false, additionalAccounts = [] }) => {
I will remove this component, it's not used anywhere in the final version of this PR. (The account picker located in the header is used instead).

2022-10-24 21:18 UTC, tien requested changes
Look solid overall, just couple of comments. Also:
- The SVG icons should be rendered at runtime instead of hard coded
- Couple places here n there should use optional chaining `maybeValue?.value` & nullish coalescing `maybeValue ?? defaultValue` (I only pointed out a couple example in this PR)

Things that are good to have later on:
- Components should be created free of business logic, documented with Storybook and live under `components/(atoms|molecules|recipes)`
- Use emotion in-line object styles instead of the `styled` API

2022-10-24 21:18 UTC, tien commented on src/archetypes/Transaction/ClickToCopy.tsx
> +`
This is not specific to just transaction and doesn't contain any business logic. So should be pushed to component later, documented with storybook, so it could be reusable elsewhere.

2022-10-24 21:18 UTC, tien commented on src/archetypes/Transaction/Item.tsx
> +    () => accounts.find(({ address }) => address === youAddress)?.name || youAddress,
`||` should be replaced with `??`

2022-10-24 21:18 UTC, tien commented on src/archetypes/Transaction/Item.tsx
> +    if (parsed.__typename !== 'ParsedTransfer') return startCase(parsed.__typename.replace(/^Parsed/, ''))
Using switch statement could potentially be clearer here? Not too sure since can `__typename` be any anything beside a string?

2022-10-24 21:18 UTC, tien commented on src/archetypes/Transaction/Item.tsx
> +  const isParsed = !!parsed
Double bang could potentially be dangerous in some cases, better to do explicit check imo.

2022-10-24 21:18 UTC, tien commented on src/archetypes/Transaction/ItemDetails.tsx
> +  if (!parsed || parsed.__typename === undefined) return <div />
can be `parsed?.__typename === undefined` instead

2022-10-27 23:27 UTC, tien requested changes
Yeh, looking good. Do you know why all the icon got changed, though?

Can you undo those svg changes for now? Cuz I rmb applying some adjustment in the code generation scripts. This might break some stuff over at noms pool.

The codegen script wasn't very polished, that's why I didn't include it in git yet. Will do that now in a separate PR

2022-10-27 23:58 UTC, alecdwm commented
> Yeh, looking good. Do you know why all the icon got changed, though?

I removed the `width` and `height` attributes, because this makes the svgs responsive by default.  
I'll revert it for the icons which aren't added by this PR!

2022-10-28 00:05 UTC, tien approved these changes
lgtm 👌

2022-10-28 00:09 UTC, alecdwm commented
<div align="center">

![ship itttttt](https://media.tenor.com/IPw1-nA5ZoUAAAAC/shipit.gif)

</div>

2022-10-28 00:09 UTC, merged