feat: Adding ORML balances to the Web-app
TalismanSociety/talisman-web pull request #310
Opened 2022-10-03 04:22 UTC by JAhimaz

This feature branch adds the ORML balances libs into the the web app.

2022-10-03 08:17 UTC, tien requested changes
I don't have context over the actual requirements, but looks good overall 💪
Only got a couple of comments

2022-10-03 08:17 UTC, tien commented on src/archetypes/Wallet/Assets.tsx
> +    if (addresses === undefined || addresses === null) return {}
I noticed we have `lodash` as dependency, so can use the utility function `isNil` to shorten this.

2022-10-03 08:17 UTC, tien commented on src/archetypes/Wallet/NewBalanceExample.tsx
> +        balance.total.planck === BigInt('0') ? null : (
- `BigInt` take a number primitive, so we can do `Bigint(0)` instead.
- Since `balance.total.planck === BigInt('0')` is an explicit conditional (evaluate to boolean), we can do `balance.total.planck === BigInt('0') && (<SomeComponent />)` without having to use ternary operator.

2022-10-03 08:17 UTC, tien commented on src/archetypes/Wallet/NewBalanceExample.tsx
> +            <img alt="token logo" src={balance.token?.logo} style={{ height: '2rem', borderRadius: '9999999rem' }} />
I don't have enough context here, but we can also achieve a round border by using `borderRadius: '100%'`

2022-10-03 08:17 UTC, tien commented on src/archetypes/Wallet/NewBalanceExample.tsx
> +            <span>{balance.chain?.name || balance.evmNetwork?.name}</span>
Same as above, better to use `??` here.

2022-10-03 08:17 UTC, tien commented on src/archetypes/Wallet/NewBalanceExample.tsx
> +                : ' -'}
Same as above, this could also benefit from using `toLocaleString` & nullish coalescing.

2022-10-03 08:17 UTC, tien commented on src/archetypes/Wallet/NewBalanceExample.tsx
> +}
I just realized that this function is duplicated of couple times. Is it possible to have this extracted to a shared hook?

2022-10-03 08:17 UTC, tien commented on src/archetypes/Wallet/Total.tsx
> +  : <Loader />
Same as above, this could also benefit from using `toLocaleString` & nullish coalescing.

2022-10-04 01:46 UTC, JAhimaz commented on src/archetypes/Wallet/Assets.tsx
> +  if(tokenAmount === '0') return null
Ah this was a test for when we were trying to figure out the BigInt issue. it has been reverted.

2022-10-04 01:47 UTC, JAhimaz commented on src/archetypes/Wallet/NewBalanceExample.tsx
> +}
@alecdwm possibly include in the library as well?

2022-10-04 15:16 UTC, alecdwm commented on src/archetypes/Wallet/NewBalanceExample.tsx
> +            <img alt="token logo" src={balance.token?.logo} style={{ height: '2rem', borderRadius: '9999999rem' }} />
I'm not sure if it's relevant to this specific case, but `100%` behaves differently to `9999999rem` when the element can't fit. For example:

![Screen Shot 2022-10-05 at 01 09 51](https://user-images.githubusercontent.com/2741569/193856797-43ec75f3-7a68-4ec0-ac77-cd5443a2f5b9.png)

[more deets](https://stackoverflow.com/a/29966500/3926156)

2022-10-04 23:34 UTC, tien commented on src/archetypes/Wallet/NewBalanceExample.tsx
> +            <img alt="token logo" src={balance.token?.logo} style={{ height: '2rem', borderRadius: '9999999rem' }} />
Oh damn, actually didn't think of this case before. Yeah, ignore if this applied here

2022-10-05 03:48 UTC, alecdwm commented on package.json
>      "@talismn/api-react-hooks": "~0",
Let's ditch this as part of this PR! ✨

2022-10-05 03:48 UTC, alecdwm commented on package.json
>      "@talismn/api-react-hooks": "~0",
(`@talismn/api-react-hooks` and `@talismn/chaindata-js`)

2022-10-05 04:35 UTC, JAhimaz commented on package.json
>      "@talismn/api-react-hooks": "~0",
Might want to clean it up a bit as some stuff still utilises `@talismn/api-react-hooks`. On the otherhand, `@talismn/chaindata-js` is not used except in crowdloans but the merge should deprecate that.

2022-10-05 10:15 UTC, JAhimaz commented on src/archetypes/Wallet/Assets.tsx
> +    if (addresses === undefined || addresses === null) return {}
```
function useAddressesByToken(addresses: string[] | null | undefined, tokenIds: Token['id'][]) {
  return useMemo(() => {
    if (isNil(addresses)) return {}
    return Object.fromEntries(tokenIds.map(tokenId => [tokenId, addresses]))
  }, [addresses, tokenIds])
}
```

Done :)

2022-10-05 12:53 UTC, JAhimaz reviewed
It's pretty outdated now, but I've updated it with most of the changes you had commented on @tien

2022-10-05 22:56 UTC, tien requested changes
Got a couple more comments. Feel free to reach out if you have any questions :D

2022-10-05 22:56 UTC, tien commented on src/archetypes/Account/Button.tsx
> +              let fiatBalance = null
Rather than using `let` & mutation here, we could use a ternary operator on `address` instead.

2022-10-05 22:56 UTC, tien commented on src/archetypes/Account/Button.tsx
> +                        <Pendor prefix={!fiatBalance && '-'}>{fiatBalance}</Pendor>
If `prefix` evaluate to `false`, will we end up with a string "false" here?

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Assets.tsx
> +  let tokenBalances = null
Same here, avoid using `let` and mutation if possible.

2022-10-05 22:56 UTC, tien commented on src/archetypes/Account/Button.tsx
> +                    : '-'
- When check the type definition for `transferable` it's a `number` only, is the type definition for that incorrect hence we have to check for type `number` here?
- `transferable || 0` could be `transferable ?? 0` instead, for explicit null check.

I believe this would be much cleaner

```tsx
(balances?.find({ tokenId: token.id }).sum.fiat('usd').transferable ?? 0)
  .toLocaleString(undefined, {
    style: 'currency',
    currency: 'USD',
    currencyDisplay: 'narrowSymbol',
  }) ?? ' -';
```

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Assets.tsx
> +      : '-'
Same as above, see my comment on line: `src/archetypes/Account/Button.tsx:119`

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Assets.tsx
> +  const address = useActiveAccount().address
Can do this instead
```ts
const { address } = useActiveAccount();
```

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Assets.tsx
> +  let fiatTotal: string | null = ''
Same as above, try to avoid using `let` & mutation.

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Assets.tsx
> +        : '-'
Same as above, see my comment on line: `src/archetypes/Account/Button.tsx:119`.

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Assets.tsx
> +      <Panel title={t('Assets')} subtitle={!balances ? <Loader /> : fiatTotal}>
In this case `!balances` could give the wrong behaviour as if user doesn't have any balance & loading has finished: `![]` will evaluate to false.

@JAhimaz @alecdwm but in all cases, it's always better to do explicit check anyway `someValue !== undefined` rather than `!someValue`

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Assets.tsx
> +              .map(token => <AssetBalance key={token.id} token={token} balances={balances} address={address} />)
For complex operation like this, better to extract this out into a `useMemo`, so that this doesn't get run on every render.

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Assets.tsx
> +          {value === 0 && !!address ? (
`!!address` lots of implicit checks like this throughout the PR. @JAhimaz can you find and replace them with explicit check if possible?

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Assets.tsx
> +                  }).format(0)}
Better to use `toLocaleString` here. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Assets.tsx
> +                  }).format(0)}
Same as above, unless for specific case, or when we want to share the `NumberFormat` instance better to use [toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString)

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Assets.tsx
> +          {value === 0 && !!address ? (
Also with explicit comparison, you don't have to use ternary operator any more, just `&&` would be sufficient.

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Assets.tsx
> +  const placeholderAssets = ['🍜', '🍜', '🍜', '🍜', '🍜']
This is fine, but just food for thought we can also do this :)
```ts
const placeholderAssets = Array(5).fill('🍜');
```

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Assets.tsx
> +`
If you rebase from `prod`. We have `emotion` as opposed to `styled-components`. So you can start declaring CSS as in-line object. Would be good if you can try it out and get a hang of it.

reference: https://emotion.sh/docs/object-styles

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Assets.tsx
> +  return null
It's always better to return unhappy path early:
- Always cover for error, unhappy path first
- Allow us to reduce nesting level

like so: `if (chain === undefined) return undefined`

Also, `chain.parathreads || []` can be `chain.parathreads ?? []`

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Total.tsx
> +  let fiatTotal: string | null = null
Same as above, try to avoid using `let` and mutation.

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Total.tsx
> +        : '-'
Same as above, see my comment on line: `src/archetypes/Account/Button.tsx:119`.

2022-10-05 22:56 UTC, tien commented on src/archetypes/Wallet/Total.tsx
> +        <span>{!!fiatTotal ? fiatTotal : <StyledLoader />}</span>
can do `fiatTotal ?? <StyledLoader />`

2022-10-05 22:56 UTC, tien commented on src/components/Panel.tsx
> +          {!!subtitle && <span>{subtitle}</span>}
Better to do explicit condition here rather than using double bang `!!`

2022-10-05 22:56 UTC, tien commented on src/layout/StateBanner/index.tsx
> +  let hasEmptyBags = false
Same as above, try to avoid using `let` and mutation.

2022-10-05 22:56 UTC, tien commented on src/libs/portfolio/index.tsx
> +    const hasEmptyBags = false
Can we double-check if this is the desired constant?

2022-10-05 22:56 UTC, tien commented on src/libs/talisman/balances.tsx
> +function useContext() {
Can we rename this to `useBalanceContext` and leave `React.useContext` as is, to avoid confusion.

2022-10-05 22:56 UTC, tien commented on src/libs/talisman/balances.tsx
> +      : null
Same as above, see my comment on line: `src/archetypes/Account/Button.tsx:119`

2022-10-06 00:20 UTC, JAhimaz commented on src/archetypes/Account/Button.tsx
> +                    : '-'
@alecdwm

2022-10-06 00:48 UTC, JAhimaz commented on src/archetypes/Wallet/Assets.tsx
> +`
Will do! Will start using emotion from now on.

2022-10-06 01:32 UTC, tien approved these changes
🚢 it 🔥

2022-10-06 04:32 UTC, JAhimaz commented
Away we go 🚀

2022-10-06 04:32 UTC, merged