fix: fixed issues with nfts attributes trying to access objects within objects
TalismanSociety/talisman-web pull request #407
Opened 2022-11-24 07:57 UTC by JAhimaz

…ttributes

2022-11-24 09:15 UTC, tien requested changes

2022-11-24 09:15 UTC, tien commented on apps/web/src/archetypes/NFT/Modal/NftDialog.tsx
> +  console.log(nft)
Prolly should remove this

2022-11-24 15:31 UTC, JAhimaz reviewed
Done, sigh silly mistake.

2022-11-25 00:04 UTC, tien approved these changes
lgtm

2022-11-25 00:05 UTC, merged