feat/portfolio-v2
TalismanSociety/talisman-web pull request #415
Opened 2022-12-06 05:41 UTC by JAhimaz

- Newly designed portfolio page
- New mini navigation bar
- Overview page showing four NFTs and 8 assets, though with searching capabilities
- Assets page for all assets, including locked.
- NFTs page reworked to show all assets per account
- Transaction History Page

2022-12-06 05:42 UTC, JAhimaz commented
Known issue:

Input is too slow/laggy. Most likely cause is the time it takes to filter or if the component for displaying assets is rendering way too many times.

2022-12-06 07:25 UTC, tien requested changes
Got a couple of comments so far. Can you also patch up the `any` types. Will go through a second round of review for this PR tmr

2022-12-06 07:25 UTC, tien commented on apps/web/src/archetypes/NFT/HiddenNFTGrid.tsx
> +          <NFTCard isBlank={true} />
Optional but can be shortened to

```jsx
<NFTCard isBlank />
```

2022-12-06 07:25 UTC, tien commented on apps/web/src/archetypes/NFT/HiddenNFTGrid.tsx
> +          <NFTCard isBlank={true} />
There are a few other places in this PR that can be benefitted from the same shorthand.

2022-12-06 07:25 UTC, tien commented on apps/web/src/routes/Assets.tsx
> +            tokens.map((token, i) => <Asset key={token?.tokenDetails?.id} token={token} balances={balances} />)}
Can be `token?.map`

2022-12-06 07:26 UTC, tien commented on apps/web/package.json
> +    "react-countup": "^6.4.0",
We already have `framer-motion` is there away to use that instead?

2022-12-06 07:27 UTC, tien commented on apps/web/src/components/molecules/DisplayValue/DisplayValue.tsx
> +import { useCallback, useMemo } from 'react'
This component feels more like an `Atom` rather than `Molecule`

2022-12-06 07:32 UTC, tien commented on apps/web/src/components/molecules/DisplayValue/DisplayValue.tsx
> +import { useCallback, useMemo } from 'react'
Also, can you test whether this is the culprit for the slow search performance?

2022-12-06 07:34 UTC, tien commented on apps/web/src/components/molecules/DisplayValue/DisplayValue.tsx
> +  const formatted = useMemo(() => format(amount), [amount, format])
can these 2 be merged into a single useMemo hook?

2022-12-07 03:05 UTC, tien commented on apps/web/package.json
> +    "react-countup": "^6.4.0",
NVM, if the extension already used this then this is better for consistency.

2022-12-12 02:26 UTC, tien requested changes

2022-12-12 02:26 UTC, tien commented on apps/web/src/components/recipes/NFTPreview/NFTPreview.tsx
> +  const [fetchedType, setFetchedType] = useState<string | undefined>()
`useState<string>()`

2022-12-12 02:26 UTC, tien commented on apps/web/src/components/recipes/NFTPreview/NFTPreview.tsx
> +    if (!fetchedType && nft?.mediaUri) {
`nft?.mediaUri !== undefined`

2022-12-12 02:26 UTC, tien commented on apps/web/src/components/recipes/NFTPreview/NFTPreview.tsx
> +      setIsLoading(false)
should be set to false once promise is resolved

2022-12-12 02:26 UTC, tien commented on apps/web/src/components/recipes/NFTPreview/NFTPreview.tsx
> +            !isFull && !nft?.mediaUri.endsWith('gif' || 'jpeg' || 'jpg' || 'png')
`'gif' || 'jpeg' || 'jpg' || 'png'` will always be `true`

2022-12-12 02:26 UTC, tien commented on apps/web/src/components/recipes/NFTPreview/NFTPreview.tsx
> +      return nft?.thumb && !isFull ? (
Do explicit check

2022-12-12 02:26 UTC, tien commented on apps/web/src/components/recipes/NFTPreview/NFTPreview.tsx
> +            event.target.pause()
Remove `any` types. Use `currentTarget` to get the correct type

2022-12-12 02:26 UTC, tien commented on apps/web/src/components/recipes/NFTPreview/NFTPreview.tsx
> +      return nft?.thumb && !isFull ? (
Explicit check if possible

2022-12-12 02:26 UTC, tien commented on apps/web/src/components/recipes/NFTPreview/NFTPreview.tsx
> +      ) : nft?.mediaUri && isFull ? (
Explicit check if possible

2022-12-12 02:26 UTC, tien commented on apps/web/src/components/recipes/NFTPreview/NFTPreview.tsx
> +      return nft?.thumb && !isFull ? (
Explicit check if possible

2022-12-12 02:26 UTC, tien commented on apps/web/src/components/recipes/NFTPreview/NFTPreview.tsx
> +      ) : nft?.mediaUri && isFull ? (
^

2022-12-12 02:26 UTC, tien commented on apps/web/src/components/recipes/NFTPreview/NFTPreview.tsx
> +          {nft?.thumb ? (
^

2022-12-12 02:26 UTC, tien commented on apps/web/src/index.tsx
> +  // </React.StrictMode>
Undo this

2022-12-12 02:26 UTC, tien commented on apps/web/src/routes/Assets.tsx
> +        </AssetsList>
can be shorten to `tokens?.map`

2022-12-12 02:26 UTC, tien commented on apps/web/src/routes/Assets.tsx
> +            tokens
^

2022-12-12 02:26 UTC, tien commented on apps/web/src/routes/NFTsPage.tsx
> +    <ExtensionStatusGate unavailable={<ExtensionUnavailable />}>
Check if we still use `ExtensionStatusGate`

2022-12-12 02:26 UTC, tien commented on apps/web/src/routes/Overview.tsx
> +  console.log({ items, isFetching, count })
remove console.log

2022-12-12 02:26 UTC, tien commented on apps/web/src/routes/Overview.tsx
> +    if (!isFetching && !items.length) {
Explicit check

2022-12-12 02:26 UTC, tien commented on apps/web/src/routes/Overview.tsx
> +      return Array.from({ length: 4 }).map((_, index) => <NFTCard isBlank />)
Missing `key` props

2022-12-12 02:26 UTC, tien commented on apps/web/src/routes/Overview.tsx
> +    return Array.from({ length: 2 }).map((_, index) => <NFTCard loading={true} />)
Missing `key` props

2022-12-12 02:26 UTC, tien commented on apps/web/src/routes/Overview.tsx
> +      return items.slice(0, 4).map((nft: any) => <NFTCard key={nft.id} nft={nft} />)
Remove `any` type

2023-01-26 02:32 UTC, tien requested changes

2023-01-26 02:32 UTC, tien commented on apps/web/src/routes/index.tsx
> +  // { path: '*', element: <Navigate to="/" /> },
Are there a reason for this to be commented out?

2023-01-26 02:32 UTC, tien commented on apps/web/src/libs/@talisman-nft/worker.js
> +}
Not sure if this will provide any performance improvements

2023-01-26 02:42 UTC, JAhimaz commented on apps/web/src/routes/index.tsx
> +  // { path: '*', element: <Navigate to="/" /> },
No it shouldn't, I was doing testing for routes and must have forgotten to uncomment. Good catch!

2023-01-26 12:19 UTC, tien requested changes

2023-01-26 12:19 UTC, tien commented on apps/web/e2e/portfolio/page.ts
> +}
Can you delete this no longer needed file

2023-01-26 12:19 UTC, tien commented on apps/web/src/App.tsx
> -                <CookieBanner />
I believe this was removed by accident

2023-01-26 12:19 UTC, tien commented on apps/web/src/archetypes/NFT/List.tsx
> +  }
The if statement above test for `address === undefined` so this will always be true. There's no need to wrap it in an if statement

2023-01-26 12:19 UTC, tien commented on apps/web/src/archetypes/NFT/Modal/NftDialog.tsx
> +          <NFTPreview nft={nft} loading={loading} isFull={true} />
`isFull={true}` can be shortened to `isFull`

2023-01-26 12:19 UTC, tien commented on apps/web/src/libs/@talisman-nft/hooks.ts
> +// rename to useNFTData
This comment is no longer needed

2023-01-30 00:52 UTC, tien approved these changes
That's it. LGTM

2023-01-30 01:11 UTC, merged