feat: integrate with signet sdk
TalismanSociety/talisman-web pull request #954
Opened 2024-01-29 06:08 UTC by chrisling-dev

2024-01-29 10:02 UTC, tien commented
lgtm, @chrisling-dev There's also `useExtrinsicBatch` which is deprecated & used in one place only. Can you either add signet support to that or just migrate the 1 usage over to `useExtrinsic` instead?

2024-01-29 11:55 UTC, tien requested changes
Just couple of minor points, also the previous msg about `useExtrinsicBatch`, everything else look good 💪

2024-01-29 11:55 UTC, tien commented on apps/web/src/domains/accounts/recoils.ts
> +    if (signetAccount) return [{ ...signetAccount, readonly: false, partOfPortfolio: true }]
Just nit-picking but would be better to do explicit check like `signetAccount !== undefined` if possible.

2024-01-29 11:55 UTC, tien commented on apps/web/src/domains/accounts/recoils.ts
> +  key: 'SignetAccountState',
The key here should be `SignetAccount`

2024-01-29 11:55 UTC, tien commented on apps/web/src/domains/accounts/recoils.ts
> +    if (inSignet && sdk) {
Do explicit `undefined` check on `sdk` if possible

2024-01-29 11:55 UTC, tien commented on apps/web/src/domains/common/hooks/useExtrinsic.ts
> +              if (error) reject(new Error(error))
Probably better to do `new Error('Some descriptive msg here', { cause: error })`

2024-01-30 05:06 UTC, chrisling-dev commented on apps/web/src/domains/accounts/recoils.ts
> +  key: 'SignetAccountState',
ahh np, using pattern from signet lol

2024-01-30 05:06 UTC, chrisling-dev commented on apps/web/src/domains/accounts/recoils.ts
> +    if (inSignet && sdk) {
I removed this check because sdk cannot be undefined in the latest version

2024-01-30 05:14 UTC, chrisling-dev commented
> lgtm, @chrisling-dev There's also `useExtrinsicBatch` which is deprecated & used in one place only. Can you either add signet support to that or just migrate the 1 usage over to `useExtrinsic` instead?

Not sure what's the best way to migrate yet given useExtrinsic doesnt return the extrinsic for batching, but instead just exposes the signAndSend function, I assume to migrate you need to build both 'staking.chill' and 'staking.unbond' as extrinsics and then batch them? 

So seems like it needs to be
```tsx
const batchExtrinsic = useExtrinsic('utility', 'batch')
...

return {
  ...
  unbondAll: async (account: string) => {
    // const chillExtrinsic = ... build chill extrinsic
    // const unbondExtrinsic = ...build unbond extrinsic
    return batchExtrinsic.signAndSend(account, {
    //  ... pass in chillExtrinsic and unbondExtrinsic
    })
  }
}
```

Lmk if you have something else in mind or I can migrate according to the snippet above

2024-01-30 05:23 UTC, tien commented
@chrisling-dev if you check the function signature of `useExtrinsic`, it also accepts either a submittable or a function that generate a submittable, so you can do something like this:

```ts
const extrinsic = useExtrinsic(useCallback((api) => api.tx.utility.batchAll([
  // ... stuffs goes here
]), []))
```

2024-01-30 07:29 UTC, chrisling-dev commented
> @chrisling-dev if you check the function signature of `useExtrinsic`, it also accepts either a submittable or a function that generate a submittable, so you can do something like this:
> 
> ```ts
> const extrinsic = useExtrinsic(useCallback((api) => api.tx.utility.batchAll([
>   // ... stuffs goes here
> ]), []))
> ```

Migrated and removed useExtrinsicBatch! Lmk wyt

2024-01-30 21:39 UTC, tien commented on apps/web/src/domains/common/hooks/useExtrinsic.ts
> +        const signingWithSignet = signetAccount !== undefined && signetAccount.address === account
Maybe this can be shortened to: `signetAccount?.address === account`

2024-01-30 21:40 UTC, tien approved these changes
lgtm

2024-01-31 03:43 UTC, chrisling-dev commented on apps/web/src/domains/common/hooks/useExtrinsic.ts
> +        const signingWithSignet = signetAccount !== undefined && signetAccount.address === account
yeap np, addressed

2024-02-01 03:00 UTC, merged